#!/bin/sh

# Set wallpaper paths
dir1=~/myconfig/wallpapers/2560x1440
dir2=~/myconfig/wallpapers/1200x1920

# decide on number of monitors
nMonitors=$(xrandr -q | rg -w "connected" | wc -l)

# if second monitor is present, select it
# TODO: Change this to a for loop over the numbers. 
# TODO: ALlow the user to choose resolution of the figure
if [ $nMonitors==2 ]; then
	wallpaper1=$(ls $dir1 | rofi -dmenu)
	wallpaper2=$(ls $dir2 | rofi -dmenu)
	feh --bg-scale $dir1/$wallpaper1 $dir2/$wallpaper2
else
	wallpaper1=$(ls $dir1 | rofi -dmenu)
	feh --bg-scale $dir1/$wallpaper1
fi



# writer wallpaper script, so the system initiates with the 
